# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9de2583b5bc568b3477cb2da20059b4818dc223efea5611d9159689380d5336642c842ad8f55b47d081a3e5d95e965501be0bec8c0592db272b39dc8dc3a41d7

test:
  secret_key_base: 01c908b3236ea6d75402a4bc7c529b4ec6beb9fdd014d455c61daf795f116019fb87a179f80569e078762bf67de2bf18efbce67858563289b2aa14d8839a3b07

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
